# Generated by Django 2.0.2 on 2022-08-01 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DeliveryAddress', '0001_initial'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressHistory',
            fields=[
                #('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeliveryAddress.DeliveryAddress')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Customer')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='addresshistory',
            unique_together={('c_id', 'a_id')},
        ),
    ]
