# Generated by Django 2.0.2 on 2022-08-01 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RestaurantManager', '0001_initial'),
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTable',
            fields=[
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestaurantManager.RestaurantManager')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.Restaurant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='admintable',
            unique_together={('m_id', 'r_id')},
        ),
    ]
