# Generated by Django 2.0.2 on 2022-08-01 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0001_initial'),
        ('FoodItem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                #('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_quantity', models.IntegerField(default=0)),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodItem.FoodItem')),
                ('o_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.Order')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='orderitems',
            unique_together={('o_id', 'f_id')},
        ),
    ]
