# Generated by Django 2.0.2 on 2022-08-01 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('DeliveryAddress', '0001_initial'),
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeliveryAddress.DeliveryAddress')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.Customer')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.Restaurant')),
            ],
        ),
    ]
